name: pr

on:
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: pr-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      python: ${{ steps.filter.outputs.python }}
    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            python:
            - '**/*.py'
            - 'pyproject.toml'

  test-python:
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.python == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install uv
      - name: Sync
        run: |
          uv sync --system
          if [[ $(git diff --stat uv.lock) != '' ]]; then
            echo 'uv.lock not up-to-date'
            git diff uv.lock
            exit 1
          fi
      - run: make fmt-check
      - run: make lint
      - run: make check
      - run: make test
