name: release
on:
  release:
    types: [published]
jobs:
  publish-all:
    environment: release
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install uv
      - run: |
          uvx --from build pyproject-build --installer uv --outdir=dist una
          uvx --from build pyproject-build --installer uv --outdir=dist plugins/hatch
      - uses: pypa/gh-action-pypi-publish@release/v1
