name: release
on:
  release:
    types: [published]
jobs:
  publish-una:
    environment: release
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: eifinger/setup-rye@v3
        id: setup-rye
        with:
          version: '0.38.0'
      - run: rye build
      - uses: pypa/gh-action-pypi-publish@release/v1

  publish-hatch-una:
    environment: release
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: eifinger/setup-rye@v3
        id: setup-rye
        with:
          version: '0.38.0'
      - run: rye build
        working-directory: plugins/hatch
      - uses: pypa/gh-action-pypi-publish@release/v1
